In [ ]:
#Create a review scrapper for https://webscraper.io/test-sites/e-commerce
/static website to fetch realtime comments, reviews, ratings, comment tags,
customer name using Python.

In [13]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [14]:
url = "https://webscraper.io/test-sites/e-commerce/static"

In [15]:
response = requests.get(url)
html_content = response.text

In [17]:
#Parse HTML
soup = BeautifulSoup(html_content, 'html.parser')

In [20]:
#Find All Products
products = soup.find_all("div", class_="thumbnail")
print("Total products: ", len(products))

Total products:  3

In [26]:

#Convert HTML Data into JSON Format all_products = []
product_data = []

for product in products:

    # Product Name
    name = product.find('a', class_='title').text.strip()

    # Price
    price = product.find('h4', class_='price').text.strip()

    # Description
    description = product.find('p', class_='description').text.strip()

# Reviews Count
review_tag = product.find('p', class_='pull-right')

if review_tag:
    reviews = review_tag.text.strip()
else:
    reviews = "No Reviews"
    # Ratings
    rating = len(product.find_all('span', class_='glyphicon-star'))

    # Tags
    tags = "Electronics Product"

    product_data.append({
        "Customer/Product Name": name,
        "Price": price,
        "Comment/Description": description,
        "Reviews": reviews,
        "Rating": rating,
        "Tags": tags
    })

In [27]:
df = pd.DataFrame(product_data)

In [28]:
df.head()

,Customer/Product Name,Price,Comment/Description,Reviews,Rating,Tags
0,Galaxy Tab 3,$107.99,"7"", 8GB, Wi-Fi, Android 4.2, Yellow",No Reviews,0,Electronics Product

In [29]:
df.to_csv("ecommerce_reviews.csv", index=False)

print("CSV File Saved Successfully")

CSV File Saved Successfully

In [31]:
top_products = df[df['Rating'] >= 2]

top_products

Empty DataFrame
Columns: [Customer/Product Name, Price, Comment/Description, Reviews, Rating, Tags]
Index: []

In [32]:
sorted_products = df.sort_values(by='Rating', ascending=False)

sorted_products.head()

,Customer/Product Name,Price,Comment/Description,Reviews,Rating,Tags
0,Galaxy Tab 3,$107.99,"7"", 8GB, Wi-Fi, Android 4.2, Yellow",No Reviews,0,Electronics Product

In [34]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Website URL
url = "https://webscraper.io/test-sites/e-commerce/static"

# Fetch Website Data
response = requests.get(url)

# Parse HTML
soup = BeautifulSoup(response.text, 'html.parser')

# Find all product cards
products = soup.find_all('div', class_='thumbnail')

# Store data
product_data = []

for product in products:

    # Product Name
    name = product.find('a', class_='title').text.strip()

    # Price
    price = product.find('h4', class_='price').text.strip()

    # Description
    description = product.find('p', class_='description').text.strip()

    # Reviews
# Reviews Count
review_tag = product.find('p', class_='pull-right')

if review_tag:
    reviews = review_tag.text.strip()
else:
    reviews = "No Reviews"
    
    # Ratings
    rating = len(product.find_all('span', class_='glyphicon-star'))

    # Tags
    tags = "Electronics Product"

    # Append data
    product_data.append({
        "Customer/Product Name": name,
        "Price": price,
        "Comment/Description": description,
        "Reviews": reviews,
        "Rating": rating,
        "Tags": tags
    })

# Convert into DataFrame
df = pd.DataFrame(product_data)

# Display data
print(df.head())

# Save into CSV
df.to_csv("ecommerce_reviews.csv", index=False)

print("Scraping Completed Successfully")

  Customer/Product Name     Price  \
0      Lenovo Legion...  $1112.91

                                 Comment/Description     Reviews  Rating  \
0  Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IP...  No Reviews       0

                  Tags
0  Electronics Product
Scraping Completed Successfully

In [35]:
print(df.head())

  Customer/Product Name     Price  \
0      Lenovo Legion...  $1112.91

                                 Comment/Description     Reviews  Rating  \
0  Lenovo Legion Y520-15IKBM, Black, 15.6" FHD IP...  No Reviews       0

                  Tags
0  Electronics Product