In [ ]:
Perform the following operations using Python on Breast Cancer data sets
i. Data cleaning(Remove NA, ?, Negative values etc.)
j. Error correcting(Outlier detection and removal)
k. Data transformation
l. Build Data model using regression and Naïve Bayes methods and compare
accuracy of benign and malignant tumors in Breast Cancer Dataset.

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv("BreastCancerWc.csv", header=None)
df.head()

        0   1   2   3   4   5   6   7   8   9   10
0  1000025   5   1   1   1   2   1   3   1   1   2
1  1002945   5   4   4   5   7  10   3   2   1   2
2  1015425   3   1   1   1   2   2   3   1   1   2
3  1016277   6   8   8   1   3   4   3   7   1   2
4  1017023   4   1   1   3   2   1   3   1   1   2

In [5]:
print("Shape:")
print(df.shape)

Shape:
(699, 11)

In [7]:
#add column name
df.columns = [
    'SampleCodeNumber',
    'ClumpThickness',
    'UniformityCellSize',
    'UniformityCellShape',
    'MarginalAdhesion',
    'SingleEpithelialCellSize',
    'BareNuclei',
    'BlandChromatin',
    'NormalNucleoli',
    'Mitoses',
    'Class'
]

In [8]:
print(df.head())

   SampleCodeNumber  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0           1000025               5                   1                    1
1           1002945               5                   4                    4
2           1015425               3                   1                    1
3           1016277               6                   8                    8
4           1017023               4                   1                    1

   MarginalAdhesion  SingleEpithelialCellSize BareNuclei  BlandChromatin  \
0                 1                         2          1               3
1                 5                         7         10               3
2                 1                         2          2               3
3                 1                         3          4               3
4                 3                         2          1               3

   NormalNucleoli  Mitoses  Class
0               1        1      2
1               2        1      2
2               1        1      2
3               7        1      2
4               1        1      2

In [9]:
print(df.columns)

Index(['SampleCodeNumber', 'ClumpThickness', 'UniformityCellSize',
       'UniformityCellShape', 'MarginalAdhesion', 'SingleEpithelialCellSize',
       'BareNuclei', 'BlandChromatin', 'NormalNucleoli', 'Mitoses', 'Class'],
      dtype='str')

In [ ]:
#data cleaning

In [11]:
# Replace '?' with NaN
df.replace('?', np.nan, inplace=True)

,SampleCodeNumber,ClumpThickness,UniformityCellSize,UniformityCellShape,MarginalAdhesion,SingleEpithelialCellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1,3,1,1,2
1,1002945,5,4,4,5,7,10,3,2,1,2
2,1015425,3,1,1,1,2,2,3,1,1,2
3,1016277,6,8,8,1,3,4,3,7,1,2
4,1017023,4,1,1,3,2,1,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2,1,1,1,2
695,841769,2,1,1,1,2,1,1,1,1,2
696,888820,5,10,10,3,7,3,8,10,2,4
697,897471,4,8,6,4,3,4,10,6,1,4
698,897471,4,8,8,5,4,5,10,4,1,4

In [13]:
for column in df.columns:
    df[column] = pd.to_numeric(df[column], errors='coerce')

In [15]:
#drop missing values
df.dropna(inplace=True)

In [16]:
#remove duplicates
df.drop_duplicates(inplace=True)

In [17]:
print(df.shape)

(675, 11)

In [19]:
#data transformation

#target column
target_column = 'Class'

# Convert:
# 2 = Benign = 0
# 4 = Malignant = 1

df[target_column] = df[target_column].apply(
    lambda x: 0 if x == 2 else 1
)

In [20]:
#separate input and output
X = df.drop(target_column, axis=1)
Y= df[target_column]

In [21]:
#feature scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [22]:
#split data
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.20, random_state = 42)

In [24]:
print(X_train.shape)
print(X_test.shape)

(540, 10)
(135, 10)

In [25]:
#logistic regression

logistic_model = LogisticRegression(max_iter=1000)

logistic_model.fit(X_train, Y_train)

logistic_prediction = logistic_model.predict(X_test)

In [26]:
logistic_accuracy = accuracy_score(Y_test, logistic_prediction)

In [27]:
#printing accuracy
print("Accuracy=", round(logistic_accuracy *100, 2), "%")

Accuracy= 95.56 %

In [28]:
#naive bayes
naive_model = GaussianNB()

naive_model.fit(X_train, Y_train)

naive_prediction = naive_model.predict(X_test)

In [29]:
naive_accuracy = accuracy_score(
    Y_test,
    naive_prediction
)

In [30]:
print("Accuracy=", round(naive_accuracy  * 100, 2), "%")

Accuracy= 96.3 %

In [32]:
print("MODEL COMPARISON")
print("===================================")

print(
    "Logistic Regression Accuracy :",
    round(logistic_accuracy * 100, 2),
    "%"
)

print(
    "Naive Bayes Accuracy :",
    round(naive_accuracy * 100, 2),
    "%"
)

MODEL COMPARISON
===================================
Logistic Regression Accuracy : 95.56 %
Naive Bayes Accuracy : 96.3 %

In [31]:
# Compare models

if logistic_accuracy > naive_accuracy:

    print(
        "\nLogistic Regression performs better."
    )

elif naive_accuracy > logistic_accuracy:

    print(
        "\nNaive Bayes performs better."
    )

else:

    print(
        "\nBoth models perform equally."
    )

Naive Bayes performs better.

In [3]:
# =========================================================
# BREAST CANCER PREDICTION PROJECT
# =========================================================
# Operations Performed:
# 1. Data Cleaning
# 2. Data Transformation
# 3. Logistic Regression Model
# 4. Naive Bayes Model
# 5. Accuracy Comparison
# =========================================================


# =========================================================
# STEP 1 : IMPORT REQUIRED LIBRARIES
# =========================================================

import pandas as pd
import numpy as np

# Machine Learning Libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Models

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

# Accuracy Metric

from sklearn.metrics import accuracy_score


# =========================================================
# STEP 2 : LOAD BREAST CANCER DATASET
# =========================================================

# Read CSV file

data = pd.read_csv(
    "BreastCancerWc.csv",
    header=None
)

print("ORIGINAL DATASET SHAPE")
print(data.shape)


# =========================================================
# STEP 3 : ADD COLUMN NAMES
# =========================================================

data.columns = [

    'SampleCodeNumber',
    'ClumpThickness',
    'UniformityCellSize',
    'UniformityCellShape',
    'MarginalAdhesion',
    'SingleEpithelialCellSize',
    'BareNuclei',
    'BlandChromatin',
    'NormalNucleoli',
    'Mitoses',
    'Class'
]

# Display first 5 rows

print("\nFIRST 5 ROWS")
print(data.head())

# Dataset shape

print("\nDATASET SHAPE")
print(data.shape)

# Display column names

print("\nCOLUMN NAMES")
print(data.columns)


# =========================================================
# STEP 4 : DATA CLEANING
# =========================================================

# -----------------------------------------
# Replace '?' with NaN
# -----------------------------------------

data.replace('?', np.nan, inplace=True)

# -----------------------------------------
# Convert all columns to numeric
# -----------------------------------------

for column in data.columns:

    data[column] = pd.to_numeric(
        data[column],
        errors='coerce'
    )

# -----------------------------------------
# Remove rows having missing values
# -----------------------------------------

data.dropna(inplace=True)

# -----------------------------------------
# Remove duplicate rows
# -----------------------------------------

data.drop_duplicates(inplace=True)

# -----------------------------------------
# Remove negative values
# -----------------------------------------

numeric_columns = data.select_dtypes(
    include=np.number
).columns

for column in numeric_columns:

    data = data[
        data[column] >= 0
    ]

# -----------------------------------------
# Display cleaned dataset
# -----------------------------------------

print("\nDATASET AFTER CLEANING")
print(data.shape)


# =========================================================
# STEP 5 : DATA TRANSFORMATION
# =========================================================

# Target column

target_column = 'Class'

# Convert:
# 2 = Benign = 0
# 4 = Malignant = 1

data[target_column] = data[target_column].apply(

    lambda x: 0 if x == 2 else 1
)

# Separate input and output

X = data.drop(target_column, axis=1)

Y = data[target_column]

# Display target values

print("\nTARGET VALUE COUNTS")
print(Y.value_counts())

# -----------------------------------------
# Feature Scaling
# -----------------------------------------

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# =========================================================
# STEP 6 : SPLIT DATA INTO TRAINING AND TESTING
# =========================================================

X_train, X_test, Y_train, Y_test = train_test_split(

    X_scaled,
    Y,

    test_size=0.20,

    random_state=42
)

print("\nTRAINING DATA SIZE")
print(X_train.shape)

print("\nTESTING DATA SIZE")
print(X_test.shape)


# =========================================================
# STEP 7 : LOGISTIC REGRESSION MODEL
# =========================================================

# Create model

logistic_model = LogisticRegression(
    max_iter=1000
)

# Train model

logistic_model.fit(
    X_train,
    Y_train
)

# Predict output

logistic_prediction = logistic_model.predict(
    X_test
)

# Calculate accuracy

logistic_accuracy = accuracy_score(

    Y_test,
    logistic_prediction
)

print("\n===================================")
print("LOGISTIC REGRESSION RESULT")
print("===================================")

print(
    "Accuracy =",
    round(logistic_accuracy * 100, 2),
    "%"
)


# =========================================================
# STEP 8 : NAIVE BAYES MODEL
# =========================================================

# Create Naive Bayes model

naive_model = GaussianNB()

# Train model

naive_model.fit(
    X_train,
    Y_train
)

# Predict output

naive_prediction = naive_model.predict(
    X_test
)

# Calculate accuracy

naive_accuracy = accuracy_score(

    Y_test,
    naive_prediction
)

print("\n===================================")
print("NAIVE BAYES RESULT")
print("===================================")

print(
    "Accuracy =",
    round(naive_accuracy * 100, 2),
    "%"
)


# =========================================================
# STEP 9 : MODEL COMPARISON
# =========================================================

print("\n===================================")
print("MODEL COMPARISON")
print("===================================")

print(
    "Logistic Regression Accuracy :",
    round(logistic_accuracy * 100, 2),
    "%"
)

print(
    "Naive Bayes Accuracy :",
    round(naive_accuracy * 100, 2),
    "%"
)

# Compare models

if logistic_accuracy > naive_accuracy:

    print(
        "\nLogistic Regression performs better."
    )

elif naive_accuracy > logistic_accuracy:

    print(
        "\nNaive Bayes performs better."
    )

else:

    print(
        "\nBoth models perform equally."
    )


# =========================================================
# END OF PROJECT
# =========================================================

ORIGINAL DATASET SHAPE
(699, 11)

FIRST 5 ROWS
   SampleCodeNumber  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0           1000025               5                   1                    1
1           1002945               5                   4                    4
2           1015425               3                   1                    1
3           1016277               6                   8                    8
4           1017023               4                   1                    1

   MarginalAdhesion  SingleEpithelialCellSize BareNuclei  BlandChromatin  \
0                 1                         2          1               3
1                 5                         7         10               3
2                 1                         2          2               3
3                 1                         3          4               3
4                 3                         2          1               3

   NormalNucleoli  Mitoses  Class
0               1        1      2
1               2        1      2
2               1        1      2
3               7        1      2
4               1        1      2

DATASET SHAPE
(699, 11)

COLUMN NAMES
Index(['SampleCodeNumber', 'ClumpThickness', 'UniformityCellSize',
       'UniformityCellShape', 'MarginalAdhesion', 'SingleEpithelialCellSize',
       'BareNuclei', 'BlandChromatin', 'NormalNucleoli', 'Mitoses', 'Class'],
      dtype='str')

DATASET AFTER CLEANING
(675, 11)

TARGET VALUE COUNTS
Class
0    439
1    236
Name: count, dtype: int64

TRAINING DATA SIZE
(540, 10)

TESTING DATA SIZE
(135, 10)

===================================
LOGISTIC REGRESSION RESULT
===================================
Accuracy = 95.56 %

===================================
NAIVE BAYES RESULT
===================================
Accuracy = 96.3 %

===================================
MODEL COMPARISON
===================================
Logistic Regression Accuracy : 95.56 %
Naive Bayes Accuracy : 96.3 %

Naive Bayes performs better.

In [5]:
# =========================================================
# BREAST CANCER PREDICTION PROJECT
# =========================================================
# Operations Performed:
# 1. Data Cleaning
# 2. Outlier Detection and Correction
# 3. Data Transformation
# 4. Logistic Regression Model
# 5. Naive Bayes Model
# 6. Accuracy Comparison
# =========================================================


# =========================================================
# STEP 1 : IMPORT REQUIRED LIBRARIES
# =========================================================

import pandas as pd
import numpy as np

# Machine Learning Libraries

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Models

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB

# Accuracy Metric

from sklearn.metrics import accuracy_score


# =========================================================
# STEP 2 : LOAD BREAST CANCER DATASET
# =========================================================

# Read CSV file

data = pd.read_csv(
    "BreastCancerWc.csv",
    header=None
)

print("ORIGINAL DATASET SHAPE")
print(data.shape)


# =========================================================
# STEP 3 : ADD COLUMN NAMES
# =========================================================

data.columns = [

    'SampleCodeNumber',
    'ClumpThickness',
    'UniformityCellSize',
    'UniformityCellShape',
    'MarginalAdhesion',
    'SingleEpithelialCellSize',
    'BareNuclei',
    'BlandChromatin',
    'NormalNucleoli',
    'Mitoses',
    'Class'
]

# Display first 5 rows

print("\nFIRST 5 ROWS")
print(data.head())

# Dataset shape

print("\nDATASET SHAPE")
print(data.shape)

# Display column names

print("\nCOLUMN NAMES")
print(data.columns)


# =========================================================
# STEP 4 : DATA CLEANING
# =========================================================

# -----------------------------------------
# Replace '?' with NaN
# -----------------------------------------

data.replace('?', np.nan, inplace=True)

# -----------------------------------------
# Convert all columns to numeric
# -----------------------------------------

for column in data.columns:

    data[column] = pd.to_numeric(
        data[column],
        errors='coerce'
    )

# -----------------------------------------
# Remove rows having missing values
# -----------------------------------------

data.dropna(inplace=True)

# -----------------------------------------
# Remove duplicate rows
# -----------------------------------------

data.drop_duplicates(inplace=True)

# -----------------------------------------
# Remove negative values
# -----------------------------------------

numeric_columns = data.select_dtypes(
    include=np.number
).columns

for column in numeric_columns:

    data = data[
        data[column] >= 0
    ]

# -----------------------------------------
# Display cleaned dataset
# -----------------------------------------

print("\nDATASET AFTER CLEANING")
print(data.shape)

# =========================================================
# STEP 5 : OUTLIER DETECTION AND CORRECTION
# =========================================================

# Columns used for outlier detection

outlier_columns = [

    'ClumpThickness',
    'UniformityCellSize',
    'UniformityCellShape',
    'MarginalAdhesion',
    'SingleEpithelialCellSize',
    'BareNuclei',
    'BlandChromatin',
    'NormalNucleoli',
    'Mitoses'
]

# Apply IQR Method

for column in outlier_columns:

    Q1 = data[column].quantile(0.25)

    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR

    upper_limit = Q3 + 1.5 * IQR

    data = data[

        (data[column] >= lower_limit) &
        (data[column] <= upper_limit)
    ]

print("\nDATASET AFTER OUTLIER REMOVAL")
print(data.shape)

# Check remaining classes

print("\nCLASS COUNTS AFTER OUTLIER REMOVAL")
print(data['Class'].value_counts())

# =========================================================
# STEP 6 : DATA TRANSFORMATION
# =========================================================

# Target column

target_column = 'Class'

# Convert:
# 2 = Benign = 0
# 4 = Malignant = 1

data[target_column] = data[target_column].apply(

    lambda x: 0 if x == 2 else 1
)

# Separate input and output

X = data.drop(target_column, axis=1)

Y = data[target_column]

# Display target values

print("\nTARGET VALUE COUNTS")
print(Y.value_counts())

# -----------------------------------------
# Feature Scaling
# -----------------------------------------

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)


# =========================================================
# STEP 7 : SPLIT DATA INTO TRAINING AND TESTING
# =========================================================

X_train, X_test, Y_train, Y_test = train_test_split(

    X_scaled,
    Y,

    test_size=0.20,

    random_state=42
)

print("\nTRAINING DATA SIZE")
print(X_train.shape)

print("\nTESTING DATA SIZE")
print(X_test.shape)


# =========================================================
# STEP 8 : LOGISTIC REGRESSION MODEL
# =========================================================

# Create model

logistic_model = LogisticRegression(
    max_iter=1000
)

# Train model

logistic_model.fit(
    X_train,
    Y_train
)

# Predict output

logistic_prediction = logistic_model.predict(
    X_test
)

# Calculate accuracy

logistic_accuracy = accuracy_score(

    Y_test,
    logistic_prediction
)

print("\n===================================")
print("LOGISTIC REGRESSION RESULT")
print("===================================")

print(
    "Accuracy =",
    round(logistic_accuracy * 100, 2),
    "%"
)


# =========================================================
# STEP 9 : NAIVE BAYES MODEL
# =========================================================

# Create Naive Bayes model

naive_model = GaussianNB()

# Train model

naive_model.fit(
    X_train,
    Y_train
)

# Predict output

naive_prediction = naive_model.predict(
    X_test
)

# Calculate accuracy

naive_accuracy = accuracy_score(

    Y_test,
    naive_prediction
)

print("\n===================================")
print("NAIVE BAYES RESULT")
print("===================================")

print(
    "Accuracy =",
    round(naive_accuracy * 100, 2),
    "%"
)


# =========================================================
# STEP 10 : MODEL COMPARISON
# =========================================================

print("\n===================================")
print("MODEL COMPARISON")
print("===================================")

print(
    "Logistic Regression Accuracy :",
    round(logistic_accuracy * 100, 2),
    "%"
)

print(
    "Naive Bayes Accuracy :",
    round(naive_accuracy * 100, 2),
    "%"
)

# Compare models

if logistic_accuracy > naive_accuracy:

    print(
        "\nLogistic Regression performs better."
    )

elif naive_accuracy > logistic_accuracy:

    print(
        "\nNaive Bayes performs better."
    )

else:

    print(
        "\nBoth models perform equally."
    )


# =========================================================
# END OF PROJECT
# =========================================================

ORIGINAL DATASET SHAPE
(699, 11)

FIRST 5 ROWS
   SampleCodeNumber  ClumpThickness  UniformityCellSize  UniformityCellShape  \
0           1000025               5                   1                    1
1           1002945               5                   4                    4
2           1015425               3                   1                    1
3           1016277               6                   8                    8
4           1017023               4                   1                    1

   MarginalAdhesion  SingleEpithelialCellSize BareNuclei  BlandChromatin  \
0                 1                         2          1               3
1                 5                         7         10               3
2                 1                         2          2               3
3                 1                         3          4               3
4                 3                         2          1               3

   NormalNucleoli  Mitoses  Class
0               1        1      2
1               2        1      2
2               1        1      2
3               7        1      2
4               1        1      2

DATASET SHAPE
(699, 11)

COLUMN NAMES
Index(['SampleCodeNumber', 'ClumpThickness', 'UniformityCellSize',
       'UniformityCellShape', 'MarginalAdhesion', 'SingleEpithelialCellSize',
       'BareNuclei', 'BlandChromatin', 'NormalNucleoli', 'Mitoses', 'Class'],
      dtype='str')

DATASET AFTER CLEANING
(675, 11)

DATASET AFTER OUTLIER REMOVAL
(359, 11)

CLASS COUNTS AFTER OUTLIER REMOVAL
Class
2    358
4      1
Name: count, dtype: int64

TARGET VALUE COUNTS
Class
0    358
1      1
Name: count, dtype: int64

TRAINING DATA SIZE
(287, 10)

TESTING DATA SIZE
(72, 10)

===================================
LOGISTIC REGRESSION RESULT
===================================
Accuracy = 100.0 %

===================================
NAIVE BAYES RESULT
===================================
Accuracy = 100.0 %

===================================
MODEL COMPARISON
===================================
Logistic Regression Accuracy : 100.0 %
Naive Bayes Accuracy : 100.0 %

Both models perform equally.