In [ ]:
Create a review scrapper for https://store.steampowered.com/appreviews
/730?json=1 website to fetch real time comments, reviews, ratings, comment
tags, customer name using Python.

In [1]:
import requests
import pandas as pd

In [8]:
url = "https://store.steampowered.com/appreviews/730?json=1"

In [9]:
#Fetch Data from Website
response = requests.get(url)
data = response.json()

In [10]:
#Check API Data
print(data.keys())

dict_keys(['success', 'query_summary', 'reviews', 'cursor'])

In [11]:
#Extract Reviews
reviews = data['reviews']
print("Total reviews fetched:", len(reviews))

Total reviews fetched: 20

In [12]:
# Extract Required Information

# Now we will extract:

# Customer Name
# Review Comment
# Rating
# Tags
# Playtime

review_data = []

for review in reviews:

    customer_name = review['author']['steamid']
    comment = review['review']
    rating = "Positive" if review['voted_up'] else "Negative"
    playtime = review['author']['playtime_forever']
    tags = review.get('weighted_vote_score', 0)

    review_data.append({
    "Customer Name": customer_name,
    "Comment": comment,
    "Rating": rating,
    "Playtime": playtime,
    "Tag Score": tags
    })

In [13]:
#Convert Data into Table
df = pd.DataFrame(review_data)

In [14]:
df.head()

,Customer Name,Comment,Rating,Playtime,Tag Score
0,76561198152982767,this game will steal a part of your soul and m...,Positive,89809,0.851908326148986816
1,76561199884102578,"Counter-Strike 2 - this isn’t a shooter, it’s ...",Positive,6899,0.825218915939331055
2,76561199141679921,Very goood game if you are from Russia or you ...,Positive,17682,0.790324985980987549
3,76561198963608852,Be respectful of others and avoid conflicts. P...,Positive,78491,0.739873826503753662
4,76561199850965103,You play well = cheater\nYou play bad = noob\n...,Negative,9405,0.740845799446105957

In [15]:
df.to_csv("data.csv", index= False)
print("generated csv")

generated csv

In [16]:
#Show Only Positive Reviews
positive_reviews = df[df['Rating'] == "Positive"]
positive_reviews.head()

,Customer Name,Comment,Rating,Playtime,Tag Score
0,76561198152982767,this game will steal a part of your soul and m...,Positive,89809,0.851908326148986816
1,76561199884102578,"Counter-Strike 2 - this isn’t a shooter, it’s ...",Positive,6899,0.825218915939331055
2,76561199141679921,Very goood game if you are from Russia or you ...,Positive,17682,0.790324985980987549
3,76561198963608852,Be respectful of others and avoid conflicts. P...,Positive,78491,0.739873826503753662
6,76561199577366977,very interesting game I broke two mice and hea...,Positive,6987,0.696195542812347412

In [17]:
negative_reviews = df[df['Rating'] == "Negative"]
negative_reviews.head()

,Customer Name,Comment,Rating,Playtime,Tag Score
4,76561199850965103,You play well = cheater\nYou play bad = noob\n...,Negative,9405,0.740845799446105957
5,76561198878876128,"Hackers hackers hackers everygame, valve doesn...",Negative,11216,0.72029566764831543
7,76561199127701778,"After 580 hours, I can confidently say my ment...",Negative,35304,0.704588055610656738
9,76561198728124380,>get prime\r\n>play cs2\r\n>get matched agains...,Negative,7147,0.623152434825897217
10,76561199813772035,Counter-Strike 2 feels like Valve took a legen...,Negative,65686,0.588583946228027344

In [19]:
#Count Total Positive and Negative Reviews
print(df['Rating'].value_counts())

Rating
Positive    10
Negative    10
Name: count, dtype: int64