In [2]:
import pandas as pd

In [6]:
df = pd.read_csv('dataset_Facebook.csv', sep=';')
df

,Page total likes,Type,Category,Post Month,Post Weekday,Post Hour,Paid,Lifetime Post Total Reach,Lifetime Post Total Impressions,Lifetime Engaged Users,Lifetime Post Consumers,Lifetime Post Consumptions,Lifetime Post Impressions by people who have liked your Page,Lifetime Post reach by people who like your Page,Lifetime People who have liked your Page and engaged with your post,comment,like,share,Total Interactions
0,139441,Photo,2,12,4,3,0.0,2752,5091,178,109,159,3078,1640,119,4,79.0,17.0,100
1,139441,Status,2,12,3,10,0.0,10460,19057,1457,1361,1674,11710,6112,1108,5,130.0,29.0,164
2,139441,Photo,3,12,3,3,0.0,2413,4373,177,113,154,2812,1503,132,0,66.0,14.0,80
3,139441,Photo,2,12,2,10,1.0,50128,87991,2211,790,1119,61027,32048,1386,58,1572.0,147.0,1777
4,139441,Photo,2,12,2,3,0.0,7244,13594,671,410,580,6228,3200,396,19,325.0,49.0,393
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,85093,Photo,3,1,7,2,0.0,4684,7536,733,708,985,4750,2876,392,5,53.0,26.0,84
496,81370,Photo,2,1,5,8,0.0,3480,6229,537,508,687,3961,2104,301,0,53.0,22.0,75
497,81370,Photo,1,1,5,2,0.0,3778,7216,625,572,795,4742,2388,363,4,93.0,18.0,115
498,81370,Photo,3,1,4,11,0.0,4156,7564,626,574,832,4534,2452,370,7,91.0,38.0,136
499,81370,Photo,2,1,4,4,NaN,4188,7292,564,524,743,3861,2200,316,0,91.0,28.0,119

In [4]:
df.head(5)

  Page total likes;Type;Category;Post Month;Post Weekday;Post Hour;Paid;Lifetime Post Total Reach;Lifetime Post Total Impressions;Lifetime Engaged Users;Lifetime Post Consumers;Lifetime Post Consumptions;Lifetime Post Impressions by people who have liked your Page;Lifetime Post reach by people who like your Page;Lifetime People who have liked your Page and engaged with your post;comment;like;share;Total Interactions
0  139441;Photo;2;12;4;3;0;2752;5091;178;109;159;...
1  139441;Status;2;12;3;10;0;10460;19057;1457;136...
2  139441;Photo;3;12;3;3;0;2413;4373;177;113;154;...
3  139441;Photo;2;12;2;10;1;50128;87991;2211;790;...
4  139441;Photo;2;12;2;3;0;7244;13594;671;410;580...

In [ ]:
# Perform the following operations using Python on the Facebook metrics data sets
# a. Create data subsets for type of post
# b. Merge two subsets
# c. Sort Data on Page total likes
# d. Transposing Data
# e. Melting Data to long format
# f. Casting data to wide format

In [7]:
subset_photo = df[df['Type'] == 'Photo']
subset_video = df[df['Type'] == 'Video']

In [9]:
print("\nPhoto Posts: ")
print(subset_photo.head())

Photo Posts:
   Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441  Photo         2          12             4          3
2            139441  Photo         3          12             3          3
3            139441  Photo         2          12             2         10
4            139441  Photo         2          12             2          3
6            139441  Photo         3          12             1          3

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091
2   0.0                       2413                             4373
3   1.0                      50128                            87991
4   0.0                       7244                            13594
6   1.0                      11692                            19479

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109
2                     177                      113
3                    2211                      790
4                     671                      410
6                     481                      265

   Lifetime Post Consumptions  \
0                         159
2                         154
3                        1119
4                         580
6                         364

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078
2                                               2812
3                                              61027
4                                               6228
6                                              15432

   Lifetime Post reach by people who like your Page  \
0                                              1640
2                                              1503
3                                             32048
4                                              3200
6                                              9328

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119
2                                                132
3                                               1386
4                                                396
6                                                379

   comment    like  share  Total Interactions
0        4    79.0   17.0                 100
2        0    66.0   14.0                  80
3       58  1572.0  147.0                1777
4       19   325.0   49.0                 393
6        3   249.0   27.0                 279

In [10]:
print("\nVideo Posts: ")
print(subset_video.head())

Video Posts:
     Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
29             138895  Video         1          12             4         11
55             138329  Video         1          11             6          2
71             137893  Video         1          11             5          3
74             137893  Video         1          11             3         11
183            134879  Video         1           9             2         10

     Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
29    1.0                      36208                            61262
55    1.0                      16416                            31950
71    1.0                     100768                           220447
74    0.0                      13544                            30235
183   0.0                      30624                            56950

     Lifetime Engaged Users  Lifetime Post Consumers  \
29                     1141                     1068
55                      459                      411
71                     2101                     1735
74                      517                      458
183                    2080                     1956

     Lifetime Post Consumptions  \
29                         1728
55                          539
71                         2331
74                          667
183                        3253

     Lifetime Post Impressions by people who have liked your Page  \
29                                               30131
55                                               21436
71                                               59658
74                                               26622
183                                              32033

     Lifetime Post reach by people who like your Page  \
29                                              14112
55                                               9568
71                                              18880
74                                              11760
183                                             15744

     Lifetime People who have liked your Page and engaged with your post  \
29                                                 559
55                                                 363
71                                                 885
74                                                 447
183                                               1376

     comment   like  share  Total Interactions
29        18  143.0   13.0                 174
55         2   65.0   14.0                  81
71        17  449.0   84.0                 550
74         2   99.0   13.0                 114
183        6  345.0  121.0                 472

In [11]:
#merge two subsets
merged_subset = pd.concat([subset_photo, subset_video])

print("\nMerge Data: ")
print(merged_subset.head())

Merge Data:
   Page total likes   Type  Category  Post Month  Post Weekday  Post Hour  \
0            139441  Photo         2          12             4          3
2            139441  Photo         3          12             3          3
3            139441  Photo         2          12             2         10
4            139441  Photo         2          12             2          3
6            139441  Photo         3          12             1          3

   Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
0   0.0                       2752                             5091
2   0.0                       2413                             4373
3   1.0                      50128                            87991
4   0.0                       7244                            13594
6   1.0                      11692                            19479

   Lifetime Engaged Users  Lifetime Post Consumers  \
0                     178                      109
2                     177                      113
3                    2211                      790
4                     671                      410
6                     481                      265

   Lifetime Post Consumptions  \
0                         159
2                         154
3                        1119
4                         580
6                         364

   Lifetime Post Impressions by people who have liked your Page  \
0                                               3078
2                                               2812
3                                              61027
4                                               6228
6                                              15432

   Lifetime Post reach by people who like your Page  \
0                                              1640
2                                              1503
3                                             32048
4                                              3200
6                                              9328

   Lifetime People who have liked your Page and engaged with your post  \
0                                                119
2                                                132
3                                               1386
4                                                396
6                                                379

   comment    like  share  Total Interactions
0        4    79.0   17.0                 100
2        0    66.0   14.0                  80
3       58  1572.0  147.0                1777
4       19   325.0   49.0                 393
6        3   249.0   27.0                 279

In [24]:
#sort data on page total likes
sorted_df = df.sort_values(by='Page total likes', ascending= False)

print("\nSorted Data: ")
print(sorted_df.head(50))

Sorted Data:
    Page total likes    Type  Category  Post Month  Post Weekday  Post Hour  \
13            139441   Photo         2          12             5          3
1             139441  Status         2          12             3         10
0             139441   Photo         2          12             4          3
5             139441  Status         2          12             1          9
4             139441   Photo         2          12             2          3
6             139441   Photo         3          12             1          3
7             139441   Photo         3          12             7          9
10            139441  Status         2          12             5         10
11            139441   Photo         2          12             5         10
2             139441   Photo         3          12             3          3
12            139441   Photo         2          12             5         10
8             139441  Status         2          12             7          3
9             139441   Photo         3          12             6         10
3             139441   Photo         2          12             2         10
39            138895   Photo         1          12             7          3
32            138895   Photo         3          12             3          3
33            138895   Photo         3          12             2          9
40            138895  Status         2          12             6         11
38            138895  Status         2          12             7          9
29            138895   Video         1          12             4         11
28            138895   Photo         2          12             5          3
35            138895   Photo         2          12             1         11
34            138895   Photo         1          12             2          3
31            138895   Photo         2          12             3         10
30            138895   Photo         2          12             4          2
37            138895   Photo         1          12             7         10
41            138895    Link         1          12             6          3
36            138895   Photo         3          12             1          3
25            138458  Status         2          12             6          3
27            138458   Photo         3          12             5          3
26            138458  Status         2          12             5         11
15            138414  Status         2          12             3         10
23            138414   Photo         3          12             7          3
24            138414  Status         2          12             6         10
14            138414   Photo         2          12             4          5
18            138414  Status         3          12             2          3
19            138414   Photo         3          12             1         11
20            138414   Photo         2          12             1          3
21            138414   Photo         1          12             7         10
22            138414    Link         1          12             7         10
16            138414   Photo         3          12             3          3
17            138414   Photo         1          12             2         12
48            138353   Photo         1          12             2         11
49            138353    Link         1          12             2          2
42            138353   Photo         1          12             5         10
46            138353  Status         1          12             3         11
47            138353    Link         1          12             3          2
45            138353    Link         1          12             4          3
44            138353   Photo         1          12             4         11
43            138353    Link         1          12             5          3

    Paid  Lifetime Post Total Reach  Lifetime Post Total Impressions  \
13   0.0                       2549                             4896
1    0.0                      10460                            19057
0    0.0                       2752                             5091
5    0.0                      10472                            20849
4    0.0                       7244                            13594
6    1.0                      11692                            19479
7    1.0                      13720                            24137
10   0.0                      21744                            42334
11   0.0                       3112                             5590
2    0.0                       2413                             4373
12   0.0                       2847                             5133
8    0.0                      11844                            22538
9    0.0                       4694                             8668
3    1.0                      50128                            87991
39   0.0                       3290                             6085
32   0.0                       5280                             9578
33   0.0                       3002                             5318
40   0.0                      13280                            24198
38   0.0                      17576                            33058
29   1.0                      36208                            61262
28   0.0                       9560                            18264
35   0.0                       4512                             7808
34   0.0                       3766                             7149
31   0.0                       1683                             2929
30   0.0                       4940                             9390
37   1.0                      19800                            28663
41   1.0                      18480                            28438
36   0.0                       2690                             4628
25   0.0                       8284                            15104
27   0.0                       2478                             4306
26   0.0                      19552                            34143
15   0.0                      10060                            19680
23   0.0                       2723                             4888
24   0.0                       8488                            15294
14   1.0                      22784                            39941
18   0.0                       3930                             7509
19   0.0                       1591                             2825
20   0.0                       2848                             5066
21   0.0                       1384                             2467
22   0.0                       3454                             6853
16   0.0                       1722                             2981
17   1.0                      53264                           111785
48   0.0                       3786                             7329
49   0.0                       1536                             3094
42   0.0                       7268                            13989
46   0.0                      16576                            30612
47   0.0                       1925                             3481
45   1.0                       7968                            13023
44   0.0                       4284                             8387
43   1.0                       2645                             4270

    Lifetime Engaged Users  Lifetime Post Consumers  \
13                     249                      134
1                     1457                     1361
0                      178                      109
5                     1191                     1073
4                      671                      410
6                      481                      265
7                      537                      232
10                    4258                     4100
11                     208                      127
2                      177                      113
12                     193                      115
8                     1530                     1407
9                      280                      183
3                     2211                      790
39                     306                      284
32                     368                      237
33                     268                      185
40                    2055                     1912
38                    5352                     5202
29                    1141                     1068
28                     973                      559
35                     423                      284
34                     298                      260
31                     192                      171
30                     385                      306
37                     479                      424
41                     517                      366
36                     252                      168
25                    1521                     1462
27                     212                      124
26                    2806                     2531
15                    1264                     1209
23                     176                      118
24                    1341                     1270
14                     887                      337
18                     130                       86
19                     121                       88
20                     200                      142
21                      15                       15
22                     118                      104
16                     163                      123
17                    1706                     1103
48                     338                      283
49                      84                       76
42                    2087                     2079
46                    3572                     3464
47                      97                       83
45                     206                      158
44                     355                      316
43                     134                      109

    Lifetime Post Consumptions  \
13                         168
1                         1674
0                          159
5                         1389
4                          580
6                          364
7                          305
10                        4540
11                         145
2                          154
12                         133
8                         1692
9                          250
3                         1119
39                         402
32                         345
33                         247
40                        2720
38                        6547
29                        1728
28                         885
35                         431
34                         431
31                         221
30                         501
37                         805
41                         460
36                         226
25                        1711
27                         149
26                        3420
15                        1425
23                         143
24                        1489
14                         417
18                         112
19                         111
20                         184
21                          20
22                         130
16                         148
17                        1655
48                         450
49                          99
42                       12074
46                        4802
47                         126
45                         223
44                         513
43                         170

    Lifetime Post Impressions by people who have liked your Page  \
13                                               3631
1                                               11710
0                                                3078
5                                               16034
4                                                6228
6                                               15432
7                                               19728
10                                              37849
11                                               3887
2                                                2812
12                                               3779
8                                               15220
9                                                4309
3                                               61027
39                                               4986
32                                               4480
33                                               3039
40                                              17627
38                                              23135
29                                              30131
28                                               9217
35                                               5183
34                                               5782
31                                               1585
30                                               5860
37                                               5187
41                                              12078
36                                               3052
25                                              10266
27                                               2612
26                                              17748
15                                              17272
23                                               2964
24                                               9684
14                                              34415
18                                               5009
19                                               2116
20                                               3561
21                                               2196
22                                               6282
16                                               1868
17                                              92512
48                                               6336
49                                               2903
42                                              13544
46                                              24363
47                                               2307
45                                               6734
44                                               7283
43                                               2330

    Lifetime Post reach by people who like your Page  \
13                                              1917
1                                               6112
0                                               1640
5                                               7852
4                                               3200
6                                               9328
7                                              11056
10                                             18952
11                                              2174
2                                               1503
12                                              2072
8                                               7912
9                                               2324
3                                              32048
39                                              2584
32                                              2422
33                                              1676
40                                              9344
38                                             11792
29                                             14112
28                                              4748
35                                              2954
34                                              2938
31                                               858
30                                              2930
37                                              2752
41                                              6752
36                                              1727
25                                              5372
27                                              1443
26                                              9824
15                                              8548
23                                              1621
24                                              5244
14                                             19312
18                                              2410
19                                              1161
20                                              1963
21                                              1172
22                                              3100
16                                              1050
17                                             39776
48                                              3216
49                                              1407
42                                              7096
46                                             12888
47                                              1180
45                                              3492
44                                              3634
43                                              1377

    Lifetime People who have liked your Page and engaged with your post  \
13                                                183
1                                                1108
0                                                 119
5                                                1016
4                                                 396
6                                                 379
7                                                 422
10                                               3798
11                                                165
2                                                 132
12                                                152
8                                                1250
9                                                 199
3                                                1386
39                                                247
32                                                268
33                                                194
40                                               1716
38                                               4104
29                                                559
28                                                621
35                                                316
34                                                244
31                                                131
30                                                273
37                                                248
41                                                319
36                                                199
25                                               1200
27                                                166
26                                               1779
15                                               1162
23                                                143
24                                                995
14                                                684
18                                                101
19                                                100
20                                                157
21                                                 15
22                                                106
16                                                123
17                                               1307
48                                                280
49                                                 76
42                                               1975
46                                               3014
47                                                 77
45                                                138
44                                                291
43                                                101

    comment    like  share  Total Interactions

In [18]:
#transpose data
transposed_df = df.transpose()

print(transposed_df.head())

                     0       1       2       3       4       5       6    \
Page total likes  139441  139441  139441  139441  139441  139441  139441
Type               Photo  Status   Photo   Photo   Photo  Status   Photo
Category               2       2       3       2       2       2       3
Post Month            12      12      12      12      12      12      12
Post Weekday           4       3       3       2       2       1       1

                     7       8       9    ...    490    491    492    493  \
Page total likes  139441  139441  139441  ...  85979  85979  85979  85093
Type               Photo  Status   Photo  ...  Photo  Photo   Link  Photo
Category               3       2       3  ...      3      3      1      3
Post Month            12      12      12  ...      1      1      1      1
Post Weekday           7       7       6  ...      6      6      5      1

                    494    495    496    497    498    499
Page total likes  85093  85093  81370  81370  81370  81370
Type              Photo  Photo  Photo  Photo  Photo  Photo
Category              3      3      2      1      3      2
Post Month            1      1      1      1      1      1
Post Weekday          7      7      5      5      4      4

[5 rows x 500 columns]

In [19]:
#melting 
melted_df = pd.melt(df,
                    id_vars=['Type'],
                    value_vars=['like', 'comment', 'share'],
                    var_name='Metric',
                    value_name='Value'
                   )

In [22]:
print("\nMelted Data: ")
print(melted_df.head())

Melted Data:
     Type Metric   Value
0   Photo   like    79.0
1  Status   like   130.0
2   Photo   like    66.0
3   Photo   like  1572.0
4   Photo   like   325.0

In [ ]:
#casting
wide_df = melted_df.pivot_table(
    index='Type',
    columns='Metric',
    values='Value',
    aggfunc='mean'
)

In [ ]:
print("\nWide format data: ")
print(wide_df